apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name }}
  namespace: {{ include "k8s-python-api-helm.namespace" . }}
type: Opaque
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}