apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name }}
  namespace: {{ include "k8s-python-api-helm.namespace" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "{{ .Values.secrets.username }}",
          "password": "{{ .Values.secrets.password }}",
          "email": "{{ .Values.secrets.email }}",
          "auth": "{{ printf "%s:%s" .Values.secrets.username .Values.secrets.password | b64enc }}"
        }
      }
    }