apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ingress.name }}-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["traefik.io"]
    resources: [
      "ingressroutes",
      "ingressroutetcps",
      "ingressrouteudps",
      "middlewares"
    ]
    verbs: ["get", "list", "watch"]