replicaCount: 1

image:
  repository: k8s-python-app
  pullPolicy: IfNotPresent
  tag: "1"

service:
  name: http # check if should not be https, then if yes how to achieve encryption
  type: ClusterIP
  port: 80
  protocol: TCP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
