replicaCount: 1

image:
  repository: ghcr.io/oleksiiakishev/k8s-microservice-deployment/k8s-python-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

service:
  name: http # check if should not be https, then if yes how to achieve encryption
  type: ClusterIP
  port: 8080
  protocol: TCP

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
